import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowUp,
  faBars,
  faBoltLightning,
  faBookOpen,
  faBriefcase,
  faBug,
  faCalendarDays,
  faChartLine,
  faCircleInfo,
  faCirclePlus,
  faCode,
  faDownload,
  faFolderPlus,
  faGaugeHigh,
  faGear,
  faGlobe,
  faGrip,
  faLayerGroup,
  faLightbulb,
  faMagnifyingGlass,
  faPaperclip,
  faPalette,
  faPlus,
  faRotateRight,
  faSliders,
  faStop,
  faTerminal,
  faThumbtack,
  faWandMagicSparkles,
} from '@fortawesome/free-solid-svg-icons';
import {
  faCircleCheck,
  faCommentDots,
  faCopy,
  faFaceSmile,
  faFileImage,
  faFolder,
  faFolderOpen,
  faNoteSticky,
  faPenToSquare,
  faTrashCan,
} from '@fortawesome/free-regular-svg-icons';

export const appIcons = {
  attachment: faPaperclip,
  autoMode: faGaugeHigh,
  chatAssistant: faWandMagicSparkles,
  chevronDown: faAngleDown,
  copy: faCopy,
  delete: faTrashCan,
  download: faDownload,
  appsGrid: faGrip,
  memory: faNoteSticky,
  personalSettings: faFaceSmile,
  folder: faFolder,
  menuCodex: faTerminal,
  menuDocumentImage: faFileImage,
  menuScheduling: faCalendarDays,
  modelAuto: faWandMagicSparkles,
  modelBalanced: faWandMagicSparkles,
  modelDeep: faLayerGroup,
  modelFast: faBoltLightning,
  modelManage: faSliders,
  moveToFolder: faFolderOpen,
  navigationMenu: faBars,
  newChat: faPenToSquare,
  newFolder: faFolderPlus,
  openPrompt: faAngleRight,
  plus: faPlus,
  pin: faThumbtack,
  rename: faPenToSquare,
  retry: faRotateRight,
  search: faMagnifyingGlass,
  selected: faCircleCheck,
  session: faCommentDots,
  settings: faGear,
  send: faArrowUp,
  stop: faStop,
  sources: faGlobe,
  reportIssue: faBug,
  info: faCircleInfo,
  addContext: faCirclePlus,
  back: faAngleLeft,
  workFolderBook: faBookOpen,
  workFolderBriefcase: faBriefcase,
  workFolderChart: faChartLine,
  workFolderCode: faCode,
  workFolderIdea: faLightbulb,
  workFolderPalette: faPalette,
} as const;
