import {
  faAngleDown,
  faAngleRight,
  faArrowUp,
  faBars,
  faBoltLightning,
  faBookOpen,
  faBrain,
  faBriefcase,
  faChartLine,
  faCircleNodes,
  faCirclePlus,
  faCode,
  faFolderPlus,
  faGaugeHigh,
  faGear,
  faGlobe,
  faLightbulb,
  faMagnifyingGlass,
  faMicrochip,
  faPaperclip,
  faPalette,
  faPlus,
  faSliders,
  faTableCellsLarge,
  faTerminal,
  faThumbtack,
  faWaveSquare,
} from '@fortawesome/free-solid-svg-icons';
import {
  faCircleCheck,
  faCommentDots,
  faFolder,
  faFolderOpen,
  faImage,
  faPenToSquare,
  faTrashCan,
} from '@fortawesome/free-regular-svg-icons';

export const appIcons = {
  attachment: faPaperclip,
  autoMode: faGaugeHigh,
  chatAssistant: faMicrochip,
  chevronDown: faAngleDown,
  delete: faTrashCan,
  folder: faFolder,
  menuApps: faTableCellsLarge,
  menuCodex: faTerminal,
  menuImage: faImage,
  menuPulse: faWaveSquare,
  modelAuto: faCircleNodes,
  modelBalanced: faMicrochip,
  modelDeep: faBrain,
  modelFast: faBoltLightning,
  modelManage: faSliders,
  moveToFolder: faFolderOpen,
  navigationMenu: faBars,
  newChat: faPenToSquare,
  newFolder: faFolderPlus,
  openPrompt: faAngleRight,
  plus: faPlus,
  pin: faThumbtack,
  rename: faPenToSquare,
  search: faMagnifyingGlass,
  selected: faCircleCheck,
  session: faCommentDots,
  settings: faGear,
  send: faArrowUp,
  sources: faGlobe,
  addContext: faCirclePlus,
  workFolderBook: faBookOpen,
  workFolderBriefcase: faBriefcase,
  workFolderChart: faChartLine,
  workFolderCode: faCode,
  workFolderIdea: faLightbulb,
  workFolderPalette: faPalette,
} as const;
