platform :ios, '26.2'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OpenEdgeAI' do
  litert_lm_frameworks_dir = File.join(__dir__, 'Frameworks')
  litert_lm_runtime_available =
    File.exist?(File.join(litert_lm_frameworks_dir, 'LiteRTLM.xcframework')) &&
    File.exist?(File.join(litert_lm_frameworks_dir, 'GemmaModelConstraintProvider.xcframework'))

  if litert_lm_runtime_available
    pod 'OpenEdgeLiteRTLMRuntime', :path => '.'
  else
    Pod::UI.warn 'LiteRT-LM iOS runtime is not linked. Run `bash scripts/build-ios-litertlm-runtime.sh sim` and then `cd ios && pod install` to enable Gemma 4 on iOS.'
  end
end
