# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OpenEdgeAI' do
  config = use_native_modules!
  litert_lm_frameworks_dir = File.join(__dir__, 'Frameworks')
  litert_lm_runtime_available =
    File.exist?(File.join(litert_lm_frameworks_dir, 'LiteRTLM.xcframework')) &&
    File.exist?(File.join(litert_lm_frameworks_dir, 'GemmaModelConstraintProvider.xcframework'))

  if litert_lm_runtime_available
    pod 'OpenEdgeLiteRTLMRuntime', :path => '.'
  else
    Pod::UI.warn 'LiteRT-LM iOS runtime is not linked. Run `bash scripts/build-ios-litertlm-runtime.sh sim` and then `cd ios && pod install` to enable Gemma 4 on iOS.'
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
