import { StyleSheet } from 'react-native';

import {
  MENU_HEADER_LOGO_LEFT_OFFSET,
  MENU_HORIZONTAL_PADDING,
  MODEL_MENU_TOP,
  MODEL_MENU_WIDTH,
  OPTION_MENU_ELEVATION,
  OPTION_MENU_Z_INDEX,
  RECENT_ACTION_MENU_WIDTH,
  WEB_APP_MAX_WIDTH,
} from './appConfig';
import { colors, typography } from '../theme/tokens';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.background,
    flex: 1,
  },
  header: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    elevation: 10000,
    flexDirection: 'row',
    minHeight: 52,
    overflow: 'visible',
    paddingHorizontal: 12,
    zIndex: 10000,
  },
  headerSide: {
    alignItems: 'flex-start',
    flexShrink: 0,
    overflow: 'visible',
    width: 112,
  },
  headerSideRight: {
    alignItems: 'flex-end',
    elevation: 10001,
    position: 'relative',
    zIndex: 10001,
  },
  menuButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  menuButtonPressed: {
    opacity: 0.55,
  },
  sessionTitle: {
    ...typography.label,
    color: colors.foreground,
    flex: 1,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '700',
    minWidth: 0,
    textAlign: 'center',
  },
  modelSelector: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: '#D3D9E3',
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    maxWidth: 104,
    minHeight: 34,
    paddingHorizontal: 9,
  },
  modelSelectorActive: {
    backgroundColor: colors.card,
    borderColor: colors.ring,
  },
  modelSelectorText: {
    ...typography.caption,
    color: colors.foreground,
    flex: 1,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    marginRight: 4,
  },
  modelMenuBackdrop: {
    bottom: 0,
    elevation: 9000,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 9000,
  },
  modelMenuOverlay: {
    backgroundColor: colors.card,
    borderColor: 'rgba(21,25,34,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    elevation: 10002,
    overflow: 'hidden',
    position: 'absolute',
    right: 12,
    shadowColor: '#000000',
    shadowOffset: { height: 16, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 26,
    top: MODEL_MENU_TOP,
    width: MODEL_MENU_WIDTH,
    zIndex: 10002,
  },
  modelMenuOption: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 56,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  modelMenuOptionDownloadable: {
    backgroundColor: colors.muted,
  },
  modelMenuOptionSelected: {
    backgroundColor: colors.accent,
  },
  modelMenuOptionDisabled: {
    opacity: 0.54,
  },
  modelMenuOptionDivider: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: 6,
  },
  modelMenuOptionValue: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    minWidth: 0,
    paddingRight: 10,
  },
  modelMenuOptionCopy: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  modelMenuOptionLabel: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  modelMenuOptionLabelDownloadable: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 22,
  },
  modelMenuOptionDescription: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '500',
    marginTop: 3,
  },
  modelMenuProgressTrack: {
    backgroundColor: colors.border,
    borderRadius: 999,
    height: 4,
    marginTop: 7,
    overflow: 'hidden',
  },
  modelMenuProgressFill: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: '100%',
  },
  modelMenuTrailingCircle: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 16,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  modelMenuDownloadPill: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 5,
    minHeight: 30,
    paddingHorizontal: 9,
  },
  modelMenuDownloadPillText: {
    ...typography.caption,
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
  },
  content: {
    flex: 1,
  },
  menuSlidePanel: {
    flex: 1,
  },
  menuWebFrame: {
    alignSelf: 'center',
    maxWidth: WEB_APP_MAX_WIDTH,
    width: '100%',
  },
  menuSafeArea: {
    backgroundColor: colors.card,
    flex: 1,
    position: 'relative',
  },
  menuFrame: {
    flex: 1,
    overflow: 'visible',
    position: 'relative',
  },
  menuBackground: {
    backgroundColor: colors.card,
    bottom: 0,
    left: 0,
    pointerEvents: 'none',
    position: 'absolute',
    right: 0,
    top: 0,
  },
  menuHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 78,
    paddingHorizontal: MENU_HORIZONTAL_PADDING,
    paddingTop: 8,
  },
  menuHeaderLogoButton: {
    alignItems: 'flex-start',
    flexShrink: 1,
    height: 44,
    justifyContent: 'center',
    marginLeft: MENU_HEADER_LOGO_LEFT_OFFSET,
    marginRight: 16,
    maxWidth: 152,
    width: 152,
  },
  menuHeaderLogo: {
    height: 32,
    width: '100%',
  },
  menuHeaderActions: {
    alignItems: 'center',
    backgroundColor: '#F7F7F8',
    borderRadius: 24,
    flexDirection: 'row',
    gap: 8,
    minHeight: 46,
    paddingHorizontal: 10,
  },
  menuSearchButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 34,
  },
  menuSettingsButton: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 34,
  },
  menuScrollContent: {
    paddingBottom: 104,
    paddingHorizontal: MENU_HORIZONTAL_PADDING,
    paddingTop: 22,
  },
  menuPrimaryList: {
    marginBottom: 34,
  },
  menuTodoBlock: {
    marginBottom: 34,
  },
  menuSectionBlock: {
    marginTop: 0,
    paddingTop: 0,
  },
  menuRecentSection: {
    marginTop: 34,
  },
  menuSectionTitle: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
    marginBottom: 8,
  },
  menuSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  menuSectionHeaderTitle: {
    marginBottom: 0,
  },
  menuSectionAddButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  menuRow: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 52,
    paddingVertical: 8,
  },
  menuRowPressed: {
    opacity: 0.58,
  },
  menuIconSlot: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    width: 46,
  },
  menuRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  menuRowLabel: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 21,
  },
  workFolderTree: {
    marginTop: 2,
  },
  workFolderTreeItem: {
    marginBottom: 2,
  },
  workFolderTreeRow: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    minHeight: 44,
  },
  workFolderTreeIconSlot: {
    height: 32,
    justifyContent: 'center',
    position: 'relative',
    width: 46,
  },
  workFolderTreeIcon: {
    alignItems: 'center',
    height: 30,
    justifyContent: 'center',
    marginLeft: 18,
    width: 24,
  },
  workFolderTreeChevron: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'center',
    position: 'absolute',
    left: 0,
    top: 3,
    width: 16,
  },
  workFolderTreeLabel: {
    ...typography.label,
    color: colors.foreground,
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 20,
    minWidth: 0,
  },
  workFolderTreeCount: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '700',
    paddingLeft: 10,
  },
  workFolderTreeChildren: {
    marginLeft: 30,
    paddingVertical: 1,
  },
  workFolderChildRow: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    minHeight: 38,
    paddingHorizontal: 2,
  },
  workFolderChildIcon: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    marginRight: 8,
    width: 20,
  },
  workFolderChildLabel: {
    ...typography.body,
    color: colors.foreground,
    flex: 1,
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 20,
    minWidth: 0,
  },
  menuRecentItem: {
    marginBottom: 2,
  },
  menuRecentRow: {
    alignItems: 'center',
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 8,
  },
  menuRecentRowActive: {
    backgroundColor: colors.muted,
  },
  menuRecentLabel: {
    ...typography.body,
    color: colors.foreground,
    flex: 1,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    paddingRight: 12,
  },
  recentActionLayer: {
    bottom: 0,
    elevation: OPTION_MENU_ELEVATION,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: OPTION_MENU_Z_INDEX,
  },
  recentActionBackdrop: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  recentFloatingActionMenu: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    elevation: OPTION_MENU_ELEVATION,
    minWidth: RECENT_ACTION_MENU_WIDTH,
    overflow: 'hidden',
    paddingVertical: 4,
    position: 'absolute',
    shadowColor: '#000000',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    zIndex: OPTION_MENU_Z_INDEX + 1,
  },
  recentActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  recentActionIcon: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    marginRight: 9,
    width: 20,
  },
  recentActionLabel: {
    ...typography.label,
    color: colors.foreground,
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  recentActionDestructiveLabel: {
    color: colors.destructive,
  },
  newChatFloatingButton: {
    alignItems: 'center',
    backgroundColor: colors.foreground,
    borderRadius: 18,
    bottom: 22,
    elevation: 32,
    flexDirection: 'row',
    minHeight: 44,
    paddingHorizontal: 16,
    position: 'absolute',
    right: 22,
    shadowColor: '#000000',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    zIndex: 35,
  },
  newChatFloatingText: {
    ...typography.label,
    color: colors.primaryForeground,
    fontSize: 14,
    fontWeight: '800',
    marginLeft: 8,
  },
  recentDialogLayer: {
    alignItems: 'center',
    bottom: 0,
    elevation: 80,
    justifyContent: 'center',
    left: 0,
    paddingHorizontal: 22,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 40,
  },
  recentDialogBackdrop: {
    backgroundColor: 'rgba(21,25,34,0.24)',
    bottom: 0,
    elevation: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  recentDialogCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    elevation: 82,
    overflow: 'visible',
    padding: 18,
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { height: 16, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
    width: '100%',
    zIndex: 1,
  },
  searchDialogCard: {
    maxHeight: '72%',
  },
  recentDialogTitle: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    marginBottom: 14,
  },
  recentDialogInput: {
    ...typography.body,
    backgroundColor: colors.muted,
    borderColor: colors.input,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.foreground,
    fontSize: 16,
    minHeight: 46,
    paddingHorizontal: 14,
  },
  workFolderNameInput: {
    flex: 1,
  },
  workFolderSettingsLabel: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 14,
  },
  workFolderMemoryInput: {
    minHeight: 112,
    paddingTop: 12,
  },
  workFolderSettingsHelp: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 17,
    marginTop: 8,
  },
  searchInputWrap: {
    alignItems: 'center',
    backgroundColor: colors.muted,
    borderColor: colors.input,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 46,
    paddingHorizontal: 14,
  },
  searchInput: {
    ...typography.body,
    color: colors.foreground,
    flex: 1,
    fontSize: 16,
    marginLeft: 10,
    minHeight: 44,
    padding: 0,
  },
  searchResultsList: {
    marginTop: 12,
  },
  searchResultRow: {
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    minHeight: 58,
    paddingHorizontal: 10,
  },
  searchResultIcon: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    marginRight: 12,
    width: 28,
  },
  searchResultCopy: {
    flex: 1,
    minWidth: 0,
  },
  searchResultTitle: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  searchResultMeta: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  searchEmptyText: {
    ...typography.label,
    color: colors.mutedForeground,
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 22,
    textAlign: 'center',
  },
  recentDialogMessage: {
    ...typography.body,
    color: colors.mutedForeground,
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 21,
  },
  workFolderSelectBlock: {
    marginTop: 14,
    position: 'relative',
    zIndex: 1,
  },
  workFolderSelectLabel: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
  workFolderSelectMenu: {
    backgroundColor: colors.card,
    borderColor: '#D9DEE8',
    borderWidth: 1,
    left: 0,
    position: 'absolute',
    right: 0,
    shadowOpacity: 0.18,
    top: 46,
  },
  workFolderSelectHelp: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
  },
  recentDialogActions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 18,
  },
  recentDialogButton: {
    alignItems: 'center',
    borderRadius: 12,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 74,
    paddingHorizontal: 14,
  },
  recentDialogPrimaryButton: {
    backgroundColor: colors.foreground,
  },
  recentDialogDeleteButton: {
    backgroundColor: colors.destructive,
  },
  recentDialogButtonDisabled: {
    opacity: 0.36,
  },
  recentDialogCancelText: {
    ...typography.label,
    color: colors.mutedForeground,
    fontSize: 15,
    fontWeight: '700',
  },
  recentDialogPrimaryText: {
    ...typography.label,
    color: colors.primaryForeground,
    fontSize: 15,
    fontWeight: '800',
  },
});
