import { StyleSheet } from 'react-native';

import {
  INITIAL_SCROLL_BOTTOM_INSET,
  THREAD_SCROLL_BOTTOM_INSET,
} from './chatTypes';
import { colors, typography } from '../../theme/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
  },
  scrollContentInitial: {
    paddingBottom: INITIAL_SCROLL_BOTTOM_INSET,
    paddingTop: 24,
  },
  scrollContentThread: {
    paddingBottom: THREAD_SCROLL_BOTTOM_INSET,
    paddingTop: 24,
  },
  hero: {
    paddingBottom: 28,
  },
  heroTitle: {
    ...typography.title,
    color: colors.foreground,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 36,
  },
  heroBody: {
    ...typography.body,
    color: colors.mutedForeground,
    fontWeight: '400',
    lineHeight: 21,
    marginTop: 10,
    maxWidth: 320,
  },
  quickSection: {
    marginBottom: 26,
  },
  modeRail: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  modeItem: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 8,
    position: 'relative',
  },
  modeItemSelected: {},
  modeText: {
    ...typography.label,
    color: colors.mutedForeground,
    fontSize: 14,
    fontWeight: '600',
  },
  modeTextSelected: {
    color: colors.primary,
  },
  modeIndicator: {
    backgroundColor: colors.primary,
    borderRadius: 2,
    bottom: -1,
    height: 3,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  threadSection: {
    marginBottom: 22,
  },
  promptList: {
    marginTop: 0,
  },
  promptRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderRadius: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 72,
    paddingHorizontal: 0,
    paddingVertical: 14,
  },
  promptRowPressed: {
    opacity: 0.58,
  },
  promptCopy: {
    flex: 1,
    paddingRight: 16,
  },
  promptTitle: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 21,
  },
  threadList: {
    paddingTop: 0,
  },
  loadingRow: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  scrollToBottomButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    height: 40,
    justifyContent: 'center',
    position: 'absolute',
    width: 40,
    zIndex: 30,
  },
  scrollToBottomButtonPressed: {
    opacity: 0.68,
  },
  composer: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    bottom: 0,
    elevation: 20,
    left: 0,
    paddingBottom: 8,
    paddingHorizontal: 12,
    paddingTop: 6,
    position: 'absolute',
    right: 0,
    zIndex: 20,
  },
  inputPanel: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    minHeight: 48,
    paddingHorizontal: 8,
    paddingVertical: 6,
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
  },
  inputRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 8,
  },
  input: {
    ...typography.body,
    backgroundColor: 'transparent',
    color: colors.foreground,
    flex: 1,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 21,
    maxHeight: 96,
    minHeight: 34,
    paddingHorizontal: 0,
    paddingTop: 6,
    textAlignVertical: 'top',
  },
  attachmentScroller: {
    marginBottom: 6,
    maxHeight: 31,
  },
  attachmentList: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 2,
  },
  attachmentChip: {
    alignItems: 'center',
    backgroundColor: colors.muted,
    borderRadius: 15,
    flexDirection: 'row',
    gap: 6,
    height: 29,
    maxWidth: 220,
    paddingLeft: 9,
    paddingRight: 5,
  },
  attachmentCopy: {
    flexShrink: 1,
    minWidth: 0,
  },
  attachmentName: {
    ...typography.caption,
    color: colors.foreground,
    fontSize: 12,
    maxWidth: 190,
  },
  attachmentMeta: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 10,
    marginTop: 2,
  },
  removeAttachmentButton: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  removeAttachmentText: {
    ...typography.label,
    color: colors.mutedForeground,
    fontSize: 13,
    lineHeight: 14,
  },
  attachmentError: {
    ...typography.caption,
    color: colors.destructive,
    paddingBottom: 6,
    paddingHorizontal: 8,
  },
  queuePanel: {
    backgroundColor: colors.muted,
    borderColor: 'rgba(21,25,34,0.08)',
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    bottom: '100%',
    left: 16,
    marginBottom: -8,
    paddingHorizontal: 8,
    paddingTop: 8,
    position: 'absolute',
    right: 16,
    zIndex: 1,
  },
  queueHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  queueTitle: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '800',
  },
  queueCount: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 10,
  },
  queueList: {
    maxHeight: 104,
  },
  queueItem: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 7,
    marginBottom: 6,
    minHeight: 42,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  queueIndexBadge: {
    alignItems: 'center',
    backgroundColor: colors.muted,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    height: 17,
    justifyContent: 'center',
    width: 17,
  },
  queueIndexText: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 9,
    fontWeight: '800',
  },
  queueItemBody: {
    flex: 1,
    minWidth: 0,
  },
  queueText: {
    ...typography.body,
    color: colors.foreground,
    fontSize: 12,
    lineHeight: 16,
  },
  queueMeta: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 10,
    marginTop: 2,
  },
  queueEditInput: {
    ...typography.body,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.foreground,
    fontSize: 12,
    lineHeight: 16,
    maxHeight: 62,
    minHeight: 36,
    paddingHorizontal: 9,
    paddingVertical: 7,
    textAlignVertical: 'top',
  },
  queueIconActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
  },
  queueIconButton: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 26,
  },
  queueTextActions: {
    alignItems: 'flex-end',
    gap: 4,
  },
  queueTextActionButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 22,
    paddingHorizontal: 4,
  },
  queueTextActionLabel: {
    ...typography.label,
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
  },
  queueTextActionLabelMuted: {
    ...typography.label,
    color: colors.mutedForeground,
    fontSize: 11,
    fontWeight: '700',
  },
  inputFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inputTools: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    paddingRight: 10,
  },
  iconTool: {
    alignItems: 'center',
    backgroundColor: colors.muted,
    borderRadius: 17,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  disabledTool: {
    opacity: 0.38,
  },
  sendButton: {
    alignItems: 'center',
    backgroundColor: colors.foreground,
    borderRadius: 17,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  sendButtonPressed: {
    opacity: 0.76,
  },
  sendButtonDisabled: {
    backgroundColor: colors.muted,
    opacity: 1,
  },
  stopButtonDisabled: {
    opacity: 0.44,
  },
});
