import { StyleSheet } from 'react-native';

import { colors, typography } from '../../theme/tokens';

export const SETTINGS_CONTENT_BOTTOM_PADDING = 42;

export const styles = StyleSheet.create({
  scroll: {
    backgroundColor: '#F4F5F8',
  },
  container: {
    paddingBottom: SETTINGS_CONTENT_BOTTOM_PADDING,
    paddingHorizontal: 24,
    paddingTop: 26,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: 22,
    paddingTop: 2,
  },
  profileLogo: {
    height: 34,
    opacity: 0.54,
    width: 152,
  },
  header: {
    marginBottom: 28,
  },
  title: {
    ...typography.title,
    color: colors.foreground,
    fontSize: 28,
    lineHeight: 34,
  },
  description: {
    ...typography.body,
    color: colors.mutedForeground,
    fontWeight: '400',
    lineHeight: 22,
    marginTop: 10,
  },
  settingsSection: {
    marginBottom: 24,
  },
  settingsSectionTitle: {
    ...typography.label,
    color: '#93969D',
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 8,
    paddingHorizontal: 16,
  },
  settingsCard: {
    backgroundColor: colors.card,
    borderColor: 'rgba(21,25,34,0.04)',
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  navigationRow: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 54,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  navigationRowDivider: {
    borderBottomColor: '#E7E7EA',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  navigationIconSlot: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    marginRight: 10,
    width: 28,
  },
  navigationCopy: {
    flex: 1,
    paddingRight: 12,
  },
  navigationTitle: {
    ...typography.body,
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '600',
  },
  navigationCaption: {
    ...typography.caption,
    color: colors.mutedForeground,
    lineHeight: 16,
    marginTop: 5,
  },
  navigationMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    maxWidth: '52%',
  },
  navigationValue: {
    ...typography.body,
    color: '#8D9097',
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '500',
  },
  section: {
    backgroundColor: colors.card,
    borderColor: 'rgba(21,25,34,0.05)',
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    marginBottom: 28,
    padding: 16,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 17,
  },
  sectionCaption: {
    ...typography.caption,
    color: colors.mutedForeground,
    marginTop: 5,
  },
  personalizationDescription: {
    ...typography.body,
    color: colors.mutedForeground,
    fontWeight: '400',
    lineHeight: 21,
    marginTop: 12,
  },
  sectionContent: {
    marginTop: 16,
  },
  textSizeList: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: 18,
  },
  textSizeRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 62,
    paddingVertical: 10,
  },
  rowPressed: {
    opacity: 0.58,
  },
  textSizeCopy: {
    flex: 1,
    paddingRight: 16,
  },
  textSizeLabel: {
    ...typography.body,
    color: colors.foreground,
    fontWeight: '500',
  },
  textSizeLabelSelected: {
    color: colors.primary,
    fontWeight: '700',
  },
  textSizeDescription: {
    ...typography.caption,
    color: colors.mutedForeground,
    lineHeight: 16,
    marginTop: 4,
  },
  fieldGroup: {
    marginTop: 16,
  },
  fieldLabel: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 15,
    marginBottom: 8,
  },
  fieldCaption: {
    ...typography.caption,
    color: colors.mutedForeground,
    lineHeight: 16,
    marginBottom: 10,
  },
  settingsTextInput: {
    ...typography.body,
    backgroundColor: colors.muted,
    borderColor: colors.input,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.foreground,
    fontSize: 15,
    lineHeight: 21,
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  longTextArea: {
    minHeight: 132,
    paddingTop: 12,
  },
  personalityList: {
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  personalityRow: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 76,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  personalityRowSelected: {
    backgroundColor: colors.accent,
  },
  personalityRowLast: {
    borderBottomWidth: 0,
  },
  personalityCopy: {
    flex: 1,
    paddingRight: 12,
  },
  personalityLabel: {
    ...typography.body,
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '600',
  },
  personalityLabelSelected: {
    color: colors.primary,
    fontWeight: '800',
  },
  personalityDescription: {
    ...typography.caption,
    color: colors.mutedForeground,
    lineHeight: 16,
    marginTop: 4,
  },
  memoryList: {
    backgroundColor: colors.muted,
    borderColor: colors.input,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  memoryListItem: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  memoryListText: {
    ...typography.body,
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 21,
  },
  emptyMemoryText: {
    ...typography.body,
    color: colors.mutedForeground,
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 21,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  languageSelect: {
    alignSelf: 'stretch',
  },
  languageOverlay: {
    flex: 1,
  },
  languageSelectTrigger: {
    alignItems: 'center',
    backgroundColor: colors.muted,
    borderColor: colors.input,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  languageSelectTriggerActive: {
    backgroundColor: colors.card,
    borderColor: colors.primary,
  },
  languageSelectValue: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  languageSelectNative: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  languageSelectEnglish: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '500',
    marginTop: 3,
  },
  languageSelectMenu: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    elevation: 96,
    overflow: 'hidden',
    position: 'absolute',
    shadowColor: '#000000',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    zIndex: 96,
  },
  languageSearchInput: {
    ...typography.body,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    color: colors.foreground,
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  languageOption: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  languageOptionActive: {
    backgroundColor: colors.accent,
  },
  languageOptionCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  languageOptionNative: {
    ...typography.label,
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  languageOptionEnglish: {
    ...typography.caption,
    color: colors.mutedForeground,
    fontSize: 12,
    fontWeight: '500',
    marginTop: 3,
  },
  languageEmptyText: {
    ...typography.body,
    color: colors.mutedForeground,
    fontSize: 15,
    lineHeight: 21,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  separator: {
    marginVertical: 14,
  },
  progressTrack: {
    backgroundColor: colors.border,
    borderRadius: 4,
    height: 8,
    marginBottom: 8,
    marginTop: 4,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: colors.primary,
    borderRadius: 4,
    height: 8,
  },
  errorText: {
    ...typography.caption,
    color: colors.destructive,
    lineHeight: 16,
    marginBottom: 8,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 8,
    marginTop: 4,
  },
  modelButton: {
    paddingHorizontal: 0,
  },
  statusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
  },
  infoList: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: 16,
  },
  infoLinkRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
  },
  infoLinkMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    maxWidth: '58%',
  },
  rowLabel: {
    ...typography.body,
    color: colors.foreground,
    flex: 1,
    fontWeight: '400',
  },
  rowValue: {
    ...typography.body,
    color: colors.mutedForeground,
    flexShrink: 1,
    fontWeight: '400',
    textAlign: 'right',
  },
  switchCopy: {
    flex: 1,
    paddingRight: 16,
  },
  toggleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 54,
  },
  settingsToggle: {
    backgroundColor: colors.input,
    borderColor: colors.border,
    borderRadius: 15,
    borderWidth: StyleSheet.hairlineWidth,
    height: 30,
    justifyContent: 'center',
    paddingHorizontal: 3,
    width: 50,
  },
  settingsToggleOn: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  settingsTogglePressed: {
    opacity: 0.72,
  },
  settingsToggleDisabled: {
    opacity: 0.54,
  },
  settingsToggleThumb: {
    backgroundColor: colors.card,
    borderRadius: 12,
    height: 24,
    shadowColor: '#000000',
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 2,
    transform: [{ translateX: 0 }],
    width: 24,
  },
  settingsToggleThumbOn: {
    transform: [{ translateX: 20 }],
  },
  refreshButton: {
    alignSelf: 'flex-start',
    marginTop: 16,
    paddingHorizontal: 0,
  },
  refreshButtonText: {
    fontSize: 16,
  },
});
